package com.startupvalidationbot.radar;

import static org.assertj.core.api.Assertions.assertThat;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.Statement;

import org.flywaydb.core.Flyway;
import org.flywaydb.core.api.MigrationVersion;
import org.junit.jupiter.api.Test;
import org.testcontainers.containers.PostgreSQLContainer;
import org.testcontainers.junit.jupiter.Container;
import org.testcontainers.junit.jupiter.Testcontainers;

@Testcontainers(disabledWithoutDocker = true)
class LegacySchemaMigrationPostgresIntegrationTest {
    @Container
    @SuppressWarnings("resource")
    static final PostgreSQLContainer<?> POSTGRES = new PostgreSQLContainer<>("postgres:16-alpine");

    @Test
    void migratesLegacyDiligenceSchemaThroughV13WithoutLosingRows() throws Exception {
        createLegacySchemaAndRows();

        var result = Flyway.configure()
                .dataSource(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword())
                .baselineOnMigrate(true)
                .baselineVersion(MigrationVersion.fromVersion("0"))
                .cleanDisabled(true)
                .validateOnMigrate(true)
                .load()
                .migrate();

        assertThat(result.targetSchemaVersion).isEqualTo("13");
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM deals WHERE company_name='Legacy Grid'"))
                    .isEqualTo(1);
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM quick_screens WHERE deal_id=1")).isEqualTo(1);
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM decisions WHERE deal_id=1")).isEqualTo(1);
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM deep_diligence WHERE deal_id=1")).isEqualTo(1);
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM reviews WHERE deal_id=1")).isEqualTo(1);
            assertThat(singleInt(statement, "SELECT COUNT(*) FROM flyway_schema_history WHERE success")).isEqualTo(14);
            assertThat(singleInt(statement, """
                    SELECT COUNT(*) FROM information_schema.tables
                     WHERE table_schema='public' AND table_name='radar_offerings'
                    """)).isEqualTo(1);
            assertThat(singleInt(statement, """
                    SELECT COUNT(*) FROM information_schema.tables
                     WHERE table_schema='public' AND table_name='radar_diligence_packets'
                    """)).isEqualTo(1);
            assertThat(singleInt(statement, """
                    SELECT COUNT(*) FROM information_schema.tables
                     WHERE table_schema='public' AND table_name='radar_campaign_discovery_results'
                    """)).isEqualTo(1);
        }
    }

    private void createLegacySchemaAndRows() throws Exception {
        try (Connection connection = connection(); Statement statement = connection.createStatement()) {
            statement.execute("""
                    CREATE TABLE deals (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        company_name VARCHAR(255) NOT NULL,
                        sector VARCHAR(255) NOT NULL,
                        platform VARCHAR(255) NOT NULL,
                        round_type VARCHAR(255) NOT NULL,
                        short_description TEXT NOT NULL,
                        valuation NUMERIC(19, 2),
                        minimum_investment NUMERIC(19, 2),
                        status VARCHAR(255) NOT NULL,
                        quick_score INTEGER NOT NULL,
                        deep_score INTEGER,
                        created_at TIMESTAMP(6) NOT NULL,
                        updated_at TIMESTAMP(6) NOT NULL
                    );
                    CREATE TABLE quick_screens (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        business_clarity INTEGER NOT NULL,
                        traction_evidence INTEGER NOT NULL,
                        edge INTEGER NOT NULL,
                        price_sanity INTEGER NOT NULL,
                        trust_transparency INTEGER NOT NULL,
                        total INTEGER NOT NULL,
                        what_is_it TEXT NOT NULL,
                        why_might_it_win TEXT NOT NULL,
                        best_proof_point TEXT NOT NULL,
                        biggest_doubt TEXT NOT NULL,
                        why_spending_time TEXT NOT NULL,
                        deal_id BIGINT NOT NULL UNIQUE REFERENCES deals(id)
                    );
                    CREATE TABLE decisions (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        status VARCHAR(255) NOT NULL,
                        rationale TEXT NOT NULL,
                        what_would_change_my_mind TEXT NOT NULL,
                        next_milestone_needed TEXT NOT NULL,
                        deal_id BIGINT NOT NULL UNIQUE REFERENCES deals(id)
                    );
                    CREATE TABLE deep_diligence (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        business_model_score INTEGER NOT NULL,
                        business_model_note TEXT NOT NULL,
                        market_customer_score INTEGER NOT NULL,
                        market_customer_note TEXT NOT NULL,
                        traction_quality_score INTEGER NOT NULL,
                        traction_quality_note TEXT NOT NULL,
                        competitive_edge_score INTEGER NOT NULL,
                        competitive_edge_note TEXT NOT NULL,
                        risk_score INTEGER NOT NULL,
                        risk_note TEXT NOT NULL,
                        total INTEGER NOT NULL,
                        deal_id BIGINT NOT NULL UNIQUE REFERENCES deals(id)
                    );
                    CREATE TABLE reviews (
                        id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
                        next_review_date DATE NOT NULL,
                        review_note TEXT NOT NULL,
                        thesis_direction VARCHAR(255) NOT NULL,
                        deal_id BIGINT NOT NULL UNIQUE REFERENCES deals(id)
                    );
                    INSERT INTO deals VALUES
                        (1, 'Legacy Grid', 'Energy', 'Republic', 'SAFE', 'Preserve this deal',
                         12000000.00, 100.00, 'WATCH', 63, 71, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);
                    INSERT INTO quick_screens VALUES
                        (1, 3, 3, 3, 2, 4, 15, 'Grid tooling', 'Growing market', 'Pilot',
                         'Early revenue', 'Verify Form C', 1);
                    INSERT INTO decisions VALUES
                        (1, 'WATCH', 'Needs evidence', 'Verified revenue', 'File Form C', 1);
                    INSERT INTO deep_diligence VALUES
                        (1, 3, 'Model', 3, 'Market', 2, 'Traction', 3, 'Edge', 2, 'Risk', 13, 1);
                    INSERT INTO reviews VALUES
                        (1, CURRENT_DATE, 'Legacy review note', 'UNCHANGED', 1);
                    """);
        }
    }

    private Connection connection() throws Exception {
        return DriverManager.getConnection(POSTGRES.getJdbcUrl(), POSTGRES.getUsername(), POSTGRES.getPassword());
    }

    private int singleInt(Statement statement, String sql) throws Exception {
        try (ResultSet rows = statement.executeQuery(sql)) {
            rows.next();
            return rows.getInt(1);
        }
    }
}
