CREATE TABLE radar_offerings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radar_company_id BIGINT REFERENCES radar_companies(id) ON DELETE SET NULL,
    issuer_name VARCHAR(300) NOT NULL,
    issuer_name_normalized VARCHAR(300) NOT NULL,
    issuer_cik VARCHAR(20) NOT NULL,
    platform VARCHAR(240) NOT NULL DEFAULT 'UNKNOWN',
    intermediary_name VARCHAR(300),
    intermediary_cik VARCHAR(20),
    offering_url VARCHAR(1200),
    sec_filing_url VARCHAR(1200) NOT NULL,
    sec_accession_number VARCHAR(32) NOT NULL,
    sec_file_number VARCHAR(80),
    filing_type VARCHAR(20) NOT NULL,
    filing_date DATE NOT NULL,
    offering_exemption VARCHAR(40) NOT NULL DEFAULT 'REG_CF',
    security_type VARCHAR(160),
    minimum_investment NUMERIC(19, 2),
    target_amount NUMERIC(19, 2),
    maximum_amount NUMERIC(19, 2),
    valuation_or_cap VARCHAR(240),
    deadline DATE,
    amount_raised NUMERIC(19, 2),
    status VARCHAR(40) NOT NULL,
    source VARCHAR(80) NOT NULL,
    match_status VARCHAR(40) NOT NULL,
    match_confidence INTEGER NOT NULL,
    match_reason VARCHAR(1000) NOT NULL,
    raw_facts_json TEXT NOT NULL DEFAULT '{}',
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_radar_offering_match_confidence CHECK (match_confidence BETWEEN 0 AND 100)
);

CREATE UNIQUE INDEX uq_radar_offerings_accession ON radar_offerings(sec_accession_number);
CREATE UNIQUE INDEX uq_radar_offerings_file_number ON radar_offerings(issuer_cik, sec_file_number);
CREATE INDEX idx_radar_offerings_company ON radar_offerings(radar_company_id, status);
CREATE INDEX idx_radar_offerings_match ON radar_offerings(match_status, last_seen_at);
CREATE INDEX idx_radar_offerings_issuer ON radar_offerings(issuer_cik, issuer_name_normalized);

CREATE TABLE radar_offering_filings (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id BIGINT NOT NULL REFERENCES radar_offerings(id) ON DELETE CASCADE,
    accession_number VARCHAR(32) NOT NULL UNIQUE,
    filing_type VARCHAR(20) NOT NULL,
    filing_date DATE NOT NULL,
    filing_url VARCHAR(1200) NOT NULL,
    facts_hash VARCHAR(64) NOT NULL,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_radar_offering_filings_offering ON radar_offering_filings(offering_id, filing_date DESC);

CREATE TABLE radar_offering_source_state (
    source_key VARCHAR(120) PRIMARY KEY,
    last_success_at TIMESTAMP,
    last_status VARCHAR(40) NOT NULL DEFAULT 'NEVER_CHECKED',
    last_error VARCHAR(2000),
    records_inspected INTEGER NOT NULL DEFAULT 0,
    updated_at TIMESTAMP NOT NULL
);
