ALTER TABLE radar_offerings ADD COLUMN last_resolution_attempt_at TIMESTAMP;
ALTER TABLE radar_offerings ADD COLUMN resolution_sources_checked TEXT NOT NULL DEFAULT '[]';
ALTER TABLE radar_offerings ADD COLUMN resolution_reason VARCHAR(1200);
ALTER TABLE radar_offerings ADD COLUMN resolution_status VARCHAR(40) NOT NULL DEFAULT 'PENDING';

CREATE TABLE radar_platform_campaigns (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    offering_id BIGINT NOT NULL REFERENCES radar_offerings(id) ON DELETE CASCADE,
    platform VARCHAR(40) NOT NULL,
    campaign_url VARCHAR(1200) NOT NULL,
    campaign_url_source VARCHAR(80) NOT NULL,
    campaign_url_confidence INTEGER NOT NULL,
    campaign_status VARCHAR(40) NOT NULL DEFAULT 'UNKNOWN',
    issuer_name VARCHAR(300),
    security_type VARCHAR(160),
    minimum_investment NUMERIC(19, 2),
    price_per_share NUMERIC(19, 6),
    valuation NUMERIC(19, 2),
    valuation_cap NUMERIC(19, 2),
    discount_percent NUMERIC(9, 4),
    target_amount NUMERIC(19, 2),
    maximum_amount NUMERIC(19, 2),
    amount_raised NUMERIC(19, 2),
    investor_count INTEGER,
    deadline DATE,
    headline VARCHAR(1000),
    facts_json TEXT NOT NULL DEFAULT '{}',
    source_fingerprint VARCHAR(64) NOT NULL,
    last_checked_at TIMESTAMP NOT NULL,
    last_verified_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_platform_campaign_confidence CHECK (campaign_url_confidence BETWEEN 0 AND 100),
    CONSTRAINT uq_platform_campaign UNIQUE (platform, campaign_url)
);

CREATE INDEX idx_platform_campaign_offering ON radar_platform_campaigns(offering_id, last_checked_at DESC);

CREATE TABLE radar_diligence_packets (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radar_company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    offering_id BIGINT NOT NULL REFERENCES radar_offerings(id) ON DELETE CASCADE,
    status VARCHAR(40) NOT NULL,
    identity_status VARCHAR(40) NOT NULL,
    completeness INTEGER NOT NULL,
    confidence INTEGER NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    bull_case TEXT NOT NULL DEFAULT '[]',
    bear_case TEXT NOT NULL DEFAULT '[]',
    key_risks TEXT NOT NULL DEFAULT '[]',
    unanswered_questions TEXT NOT NULL DEFAULT '[]',
    material_discrepancies TEXT NOT NULL DEFAULT '[]',
    next_monitoring_milestones TEXT NOT NULL DEFAULT '[]',
    sources_checked TEXT NOT NULL DEFAULT '[]',
    data_not_found TEXT NOT NULL DEFAULT '[]',
    source_fingerprint VARCHAR(64) NOT NULL,
    generated_at TIMESTAMP NOT NULL,
    last_refreshed_at TIMESTAMP NOT NULL,
    reviewed_at TIMESTAMP,
    CONSTRAINT ck_diligence_completeness CHECK (completeness BETWEEN 0 AND 100),
    CONSTRAINT ck_diligence_confidence CHECK (confidence BETWEEN 0 AND 100),
    CONSTRAINT uq_diligence_packet_offering UNIQUE (offering_id)
);

CREATE INDEX idx_diligence_queue ON radar_diligence_packets(status, last_refreshed_at DESC);

CREATE TABLE radar_diligence_evidence (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_id BIGINT NOT NULL REFERENCES radar_diligence_packets(id) ON DELETE CASCADE,
    source_type VARCHAR(60) NOT NULL,
    source_url VARCHAR(1200),
    source_title VARCHAR(500) NOT NULL,
    fact_key VARCHAR(160) NOT NULL,
    fact_value TEXT NOT NULL,
    period VARCHAR(40),
    classification VARCHAR(60) NOT NULL,
    observed_at TIMESTAMP NOT NULL,
    confidence INTEGER NOT NULL,
    raw_excerpt VARCHAR(2000),
    metadata_json TEXT NOT NULL DEFAULT '{}',
    evidence_fingerprint VARCHAR(64) NOT NULL,
    CONSTRAINT ck_diligence_evidence_confidence CHECK (confidence BETWEEN 0 AND 100),
    CONSTRAINT uq_diligence_evidence UNIQUE (packet_id, evidence_fingerprint)
);

CREATE INDEX idx_diligence_evidence_packet ON radar_diligence_evidence(packet_id, classification, fact_key);

CREATE TABLE radar_diligence_financials (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    packet_id BIGINT NOT NULL REFERENCES radar_diligence_packets(id) ON DELETE CASCADE,
    offering_id BIGINT NOT NULL REFERENCES radar_offerings(id) ON DELETE CASCADE,
    period VARCHAR(40) NOT NULL,
    revenue NUMERIC(19, 2),
    cost_of_goods NUMERIC(19, 2),
    net_income NUMERIC(19, 2),
    cash NUMERIC(19, 2),
    assets NUMERIC(19, 2),
    liabilities NUMERIC(19, 2),
    short_term_debt NUMERIC(19, 2),
    long_term_debt NUMERIC(19, 2),
    taxes_paid NUMERIC(19, 2),
    source_accession_number VARCHAR(32) NOT NULL,
    source_url VARCHAR(1200) NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_diligence_financial_period UNIQUE (packet_id, period)
);

CREATE TABLE radar_investment_availability_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radar_company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    source_type VARCHAR(40) NOT NULL,
    status VARCHAR(40) NOT NULL,
    result_summary VARCHAR(1000) NOT NULL,
    unresolved_question VARCHAR(1000),
    checked_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_investment_availability UNIQUE (radar_company_id, source_type)
);

CREATE TABLE radar_platform_source_state (
    platform VARCHAR(40) PRIMARY KEY,
    last_checked_at TIMESTAMP,
    last_status VARCHAR(40) NOT NULL DEFAULT 'NEVER_CHECKED',
    requests_made INTEGER NOT NULL DEFAULT 0,
    campaigns_found INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_notification_events (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    event_type VARCHAR(60) NOT NULL,
    entity_type VARCHAR(60) NOT NULL,
    entity_id BIGINT NOT NULL,
    fingerprint VARCHAR(64) NOT NULL,
    recipient VARCHAR(320),
    status VARCHAR(40) NOT NULL,
    subject VARCHAR(500) NOT NULL,
    text_body TEXT NOT NULL,
    html_body TEXT NOT NULL,
    resend_message_id VARCHAR(240),
    attempt_count INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    created_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_radar_notification_fingerprint UNIQUE (fingerprint)
);

CREATE INDEX idx_radar_notification_pending ON radar_notification_events(status, created_at);
