CREATE TABLE radar_campaign_discovery_checks (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radar_company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    offering_id BIGINT REFERENCES radar_offerings(id) ON DELETE CASCADE,
    platform VARCHAR(40) NOT NULL,
    identity_fingerprint VARCHAR(64) NOT NULL,
    status VARCHAR(40) NOT NULL,
    requests_made INTEGER NOT NULL DEFAULT 0,
    candidates_found INTEGER NOT NULL DEFAULT 0,
    result_summary VARCHAR(1000) NOT NULL,
    last_error VARCHAR(2000),
    checked_at TIMESTAMP NOT NULL,
    next_eligible_at TIMESTAMP NOT NULL,
    CONSTRAINT uq_campaign_discovery_check UNIQUE (radar_company_id, platform)
);

CREATE INDEX idx_campaign_discovery_due
    ON radar_campaign_discovery_checks(next_eligible_at, platform);

CREATE TABLE radar_campaign_discovery_results (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    radar_company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    offering_id BIGINT REFERENCES radar_offerings(id) ON DELETE CASCADE,
    platform VARCHAR(40) NOT NULL,
    campaign_url VARCHAR(1200) NOT NULL,
    issuer_name VARCHAR(300),
    issuer_domain VARCHAR(300),
    platform_identifier VARCHAR(300),
    evidence_source VARCHAR(1200) NOT NULL,
    discovery_confidence INTEGER NOT NULL,
    identity_status VARCHAR(40) NOT NULL,
    identity_reason VARCHAR(1200) NOT NULL,
    metadata_json TEXT NOT NULL DEFAULT '{}',
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_campaign_discovery_confidence CHECK (discovery_confidence BETWEEN 0 AND 100),
    CONSTRAINT uq_campaign_discovery_result UNIQUE (radar_company_id, platform, campaign_url)
);

CREATE INDEX idx_campaign_discovery_result_company
    ON radar_campaign_discovery_results(radar_company_id, identity_status, last_seen_at DESC);

CREATE TABLE radar_campaign_discovery_platform_state (
    platform VARCHAR(40) PRIMARY KEY,
    discovery_capability VARCHAR(120) NOT NULL,
    last_checked_at TIMESTAMP,
    last_success_at TIMESTAMP,
    last_failure_at TIMESTAMP,
    last_status VARCHAR(40) NOT NULL DEFAULT 'NEVER_CHECKED',
    requests_made INTEGER NOT NULL DEFAULT 0,
    candidates_found INTEGER NOT NULL DEFAULT 0,
    campaigns_resolved INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    updated_at TIMESTAMP NOT NULL
);
