ALTER TABLE radar_offerings ALTER COLUMN issuer_cik DROP NOT NULL;
ALTER TABLE radar_offerings ALTER COLUMN sec_filing_url DROP NOT NULL;
ALTER TABLE radar_offerings ALTER COLUMN sec_accession_number DROP NOT NULL;

ALTER TABLE radar_offerings ADD COLUMN provenance VARCHAR(40) NOT NULL DEFAULT 'SEC_EDGAR';
ALTER TABLE radar_offerings ADD COLUMN reconciliation_status VARCHAR(40) NOT NULL DEFAULT 'SEC_RECONCILED';
ALTER TABLE radar_offerings ADD COLUMN platform_status VARCHAR(40);
ALTER TABLE radar_offerings ADD COLUMN native_candidate_key VARCHAR(500);

CREATE UNIQUE INDEX uq_radar_offerings_native_candidate ON radar_offerings(native_candidate_key);
CREATE INDEX idx_radar_offerings_actionable ON radar_offerings(status, offering_exemption, updated_at DESC);

CREATE TABLE radar_native_offering_candidates (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source VARCHAR(80) NOT NULL,
    platform VARCHAR(80) NOT NULL,
    external_id VARCHAR(500) NOT NULL,
    company_name VARCHAR(300) NOT NULL,
    issuer_domain VARCHAR(300),
    issuer_website VARCHAR(1200),
    campaign_url VARCHAR(1200),
    platform_status VARCHAR(40) NOT NULL,
    offering_exemption VARCHAR(40) NOT NULL,
    intermediary_name VARCHAR(300),
    security_type VARCHAR(160),
    amount_raised NUMERIC(19, 2),
    target_amount NUMERIC(19, 2),
    maximum_amount NUMERIC(19, 2),
    valuation_or_cap VARCHAR(240),
    minimum_investment NUMERIC(19, 2),
    price_per_share NUMERIC(19, 6),
    deadline DATE,
    category VARCHAR(300),
    description VARCHAR(2000),
    issuer_cik VARCHAR(20),
    sec_accession_number VARCHAR(32),
    sec_file_number VARCHAR(80),
    sec_filing_url VARCHAR(1200),
    filing_type VARCHAR(20),
    filing_date DATE,
    reconciliation_status VARCHAR(40) NOT NULL,
    identity_status VARCHAR(40) NOT NULL,
    identity_confidence INTEGER NOT NULL,
    actionable BOOLEAN NOT NULL,
    source_evidence_json TEXT NOT NULL DEFAULT '{}',
    source_fingerprint VARCHAR(64) NOT NULL,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL,
    CONSTRAINT ck_native_offering_identity_confidence CHECK (identity_confidence BETWEEN 0 AND 100),
    CONSTRAINT uq_native_offering_candidate UNIQUE (source, external_id)
);

CREATE INDEX idx_native_offering_campaign ON radar_native_offering_candidates(platform, campaign_url);
CREATE INDEX idx_native_offering_sec ON radar_native_offering_candidates(issuer_cik, sec_file_number);
CREATE INDEX idx_native_offering_actionable ON radar_native_offering_candidates(actionable, platform_status, last_seen_at DESC);

CREATE TABLE radar_native_offering_source_state (
    source VARCHAR(80) PRIMARY KEY,
    capability VARCHAR(120) NOT NULL,
    last_checked_at TIMESTAMP NOT NULL,
    last_success_at TIMESTAMP,
    last_status VARCHAR(40) NOT NULL,
    directory_fetched BOOLEAN NOT NULL DEFAULT FALSE,
    requests_made INTEGER NOT NULL DEFAULT 0,
    detail_requests INTEGER NOT NULL DEFAULT 0,
    candidates_found INTEGER NOT NULL DEFAULT 0,
    active_candidates INTEGER NOT NULL DEFAULT 0,
    offerings_inserted INTEGER NOT NULL DEFAULT 0,
    companies_matched INTEGER NOT NULL DEFAULT 0,
    candidates_rejected INTEGER NOT NULL DEFAULT 0,
    last_error VARCHAR(2000),
    updated_at TIMESTAMP NOT NULL
);
