CREATE TABLE radar_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source_key VARCHAR(160) NOT NULL UNIQUE,
    source_type VARCHAR(40) NOT NULL,
    name VARCHAR(240) NOT NULL,
    url VARCHAR(1200),
    config_json TEXT NOT NULL DEFAULT '{}',
    enabled BOOLEAN NOT NULL DEFAULT TRUE,
    last_checked_at TIMESTAMP,
    last_status VARCHAR(40) NOT NULL DEFAULT 'NEVER_CHECKED',
    last_error TEXT,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_companies (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    normalized_name VARCHAR(300) NOT NULL,
    domain VARCHAR(300) UNIQUE,
    website_url VARCHAR(1200),
    description TEXT NOT NULL DEFAULT '',
    sector VARCHAR(160) NOT NULL DEFAULT 'Unknown',
    categories_json TEXT NOT NULL DEFAULT '[]',
    headquarters VARCHAR(240),
    founded_year INTEGER,
    aliases_json TEXT NOT NULL DEFAULT '[]',
    radar_score INTEGER NOT NULL DEFAULT 0,
    personal_score INTEGER NOT NULL DEFAULT 0,
    score_reasoning TEXT NOT NULL DEFAULT '',
    source_count INTEGER NOT NULL DEFAULT 0,
    first_seen_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    ignored BOOLEAN NOT NULL DEFAULT FALSE,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_radar_companies_normalized_name ON radar_companies(normalized_name);
CREATE INDEX idx_radar_companies_scores ON radar_companies(radar_score, personal_score);

CREATE TABLE radar_discoveries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    source_id BIGINT NOT NULL REFERENCES radar_sources(id) ON DELETE CASCADE,
    external_id VARCHAR(500) NOT NULL,
    source_url VARCHAR(1200),
    raw_text TEXT NOT NULL DEFAULT '',
    raw_text_hash VARCHAR(64) NOT NULL,
    discovered_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    UNIQUE(source_id, external_id)
);

CREATE TABLE radar_company_snapshots (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    source_id BIGINT REFERENCES radar_sources(id) ON DELETE SET NULL,
    captured_at TIMESTAMP NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    snapshot_json TEXT NOT NULL,
    notable_changes_json TEXT NOT NULL DEFAULT '[]',
    UNIQUE(company_id, input_hash)
);

CREATE TABLE radar_company_analyses (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    analysis_type VARCHAR(40) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    model VARCHAR(120) NOT NULL,
    analysis_json TEXT NOT NULL,
    radar_score INTEGER NOT NULL,
    personal_score INTEGER NOT NULL,
    created_at TIMESTAMP NOT NULL,
    UNIQUE(company_id, analysis_type, input_hash, prompt_version)
);

CREATE TABLE radar_watchlist_entries (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL UNIQUE REFERENCES radar_companies(id) ON DELETE CASCADE,
    status VARCHAR(40) NOT NULL DEFAULT 'WATCHING',
    notes TEXT NOT NULL DEFAULT '',
    next_review_at TIMESTAMP,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_investors (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name VARCHAR(300) NOT NULL,
    normalized_name VARCHAR(300) NOT NULL UNIQUE,
    website_url VARCHAR(1200),
    investor_type VARCHAR(80) NOT NULL DEFAULT 'Unknown',
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_company_investors (
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    investor_id BIGINT NOT NULL REFERENCES radar_investors(id) ON DELETE CASCADE,
    source_url VARCHAR(1200),
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY(company_id, investor_id)
);

CREATE TABLE radar_research_sources (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    source_type VARCHAR(80) NOT NULL,
    title VARCHAR(500) NOT NULL,
    url VARCHAR(1200),
    source_date TIMESTAMP,
    excerpt TEXT NOT NULL DEFAULT '',
    is_fact BOOLEAN NOT NULL DEFAULT TRUE,
    created_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_trends (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    trend_key VARCHAR(220) NOT NULL UNIQUE,
    name VARCHAR(240) NOT NULL,
    summary TEXT NOT NULL DEFAULT '',
    company_count INTEGER NOT NULL DEFAULT 0,
    momentum_score INTEGER NOT NULL DEFAULT 0,
    period_start TIMESTAMP NOT NULL,
    period_end TIMESTAMP NOT NULL,
    created_at TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);

CREATE TABLE radar_trend_companies (
    trend_id BIGINT NOT NULL REFERENCES radar_trends(id) ON DELETE CASCADE,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    relevance_score INTEGER NOT NULL DEFAULT 0,
    created_at TIMESTAMP NOT NULL,
    PRIMARY KEY(trend_id, company_id)
);

CREATE TABLE radar_digests (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    digest_type VARCHAR(40) NOT NULL,
    period_key VARCHAR(80) NOT NULL UNIQUE,
    subject VARCHAR(500) NOT NULL,
    text_body TEXT NOT NULL,
    html_body TEXT NOT NULL,
    status VARCHAR(40) NOT NULL,
    provider_message_id VARCHAR(300),
    error_message TEXT,
    generated_at TIMESTAMP NOT NULL,
    sent_at TIMESTAMP
);

CREATE TABLE radar_job_runs (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    job_type VARCHAR(80) NOT NULL,
    idempotency_key VARCHAR(160) NOT NULL,
    status VARCHAR(40) NOT NULL,
    summary_json TEXT NOT NULL DEFAULT '{}',
    error_message TEXT,
    started_at TIMESTAMP NOT NULL,
    completed_at TIMESTAMP,
    UNIQUE(job_type, idempotency_key)
);

INSERT INTO radar_sources (
    source_key, source_type, name, url, config_json, enabled,
    last_status, created_at, updated_at
) VALUES (
    'product-hunt', 'PRODUCT_HUNT', 'Product Hunt',
    'https://api.producthunt.com/v2/api/graphql', '{}', FALSE,
    'TOKEN_REQUIRED', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);

INSERT INTO radar_sources (
    source_key, source_type, name, url, config_json, enabled,
    last_status, created_at, updated_at
) VALUES (
    'yc-directory', 'YC_DIRECTORY', 'Y Combinator directory',
    'https://www.ycombinator.com/companies', '{}', FALSE,
    'MANUAL_REVIEW_ONLY', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP
);
