ALTER TABLE radar_company_analyses
    ADD COLUMN schema_version VARCHAR(80) NOT NULL DEFAULT 'radar-analysis-v1';

ALTER TABLE radar_company_analyses
    ADD COLUMN provider VARCHAR(40) NOT NULL DEFAULT 'deterministic';

ALTER TABLE radar_company_analyses
    ADD COLUMN analysis_origin VARCHAR(40) NOT NULL DEFAULT 'DETERMINISTIC';

ALTER TABLE radar_company_analyses
    ADD COLUMN status VARCHAR(40) NOT NULL DEFAULT 'SUCCESS';

CREATE TABLE radar_ai_attempts (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    analysis_type VARCHAR(40) NOT NULL,
    provider VARCHAR(40) NOT NULL,
    model VARCHAR(120) NOT NULL,
    input_hash VARCHAR(64) NOT NULL,
    prompt_version VARCHAR(80) NOT NULL,
    schema_version VARCHAR(80) NOT NULL,
    status VARCHAR(40) NOT NULL,
    error_type VARCHAR(80),
    error_message VARCHAR(1000),
    retry_count INTEGER NOT NULL DEFAULT 0,
    latency_ms BIGINT,
    input_tokens BIGINT,
    output_tokens BIGINT,
    created_at TIMESTAMP NOT NULL
);

CREATE INDEX idx_radar_ai_attempts_company_created
    ON radar_ai_attempts(company_id, created_at DESC);
