CREATE TABLE radar_admin_sessions (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash VARCHAR(64) NOT NULL UNIQUE,
    created_at TIMESTAMP NOT NULL,
    last_seen_at TIMESTAMP NOT NULL,
    expires_at TIMESTAMP NOT NULL,
    revoked_at TIMESTAMP
);

CREATE INDEX idx_radar_admin_sessions_expires
    ON radar_admin_sessions(expires_at);

CREATE TABLE radar_job_locks (
    job_type VARCHAR(80) PRIMARY KEY,
    lease_token VARCHAR(80),
    locked_until TIMESTAMP NOT NULL,
    updated_at TIMESTAMP NOT NULL
);
