-- Brings the legacy Deal Scout / diligence tables under Flyway control.
--
-- These tables were previously created implicitly by Hibernate (ddl-auto=update). This migration
-- captures that schema so Flyway becomes the single schema authority and the application can boot
-- with ddl-auto=validate.
--
-- Safety properties:
--   * CREATE TABLE IF NOT EXISTS -> non-destructive on databases where Hibernate already created
--     these tables; the existing definitions and all existing rows are left untouched.
--   * On a fresh database the definitions below reproduce the Hibernate-generated schema exactly
--     (Spring Boot CamelCaseToUnderscoresNamingStrategy, Hibernate 6 default type mappings).
--   * No DROP, no ALTER, no data movement.

CREATE TABLE IF NOT EXISTS deals (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_name       VARCHAR(255) NOT NULL,
    sector             VARCHAR(255) NOT NULL,
    platform           VARCHAR(255) NOT NULL,
    round_type         VARCHAR(255) NOT NULL,
    short_description  TEXT NOT NULL,
    valuation          NUMERIC(19, 2),
    minimum_investment NUMERIC(19, 2),
    status             VARCHAR(255) NOT NULL,
    quick_score        INTEGER NOT NULL,
    deep_score         INTEGER,
    created_at         TIMESTAMP(6) NOT NULL,
    updated_at         TIMESTAMP(6) NOT NULL
);

CREATE TABLE IF NOT EXISTS quick_screens (
    id                 BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_clarity   INTEGER NOT NULL,
    traction_evidence  INTEGER NOT NULL,
    edge               INTEGER NOT NULL,
    price_sanity       INTEGER NOT NULL,
    trust_transparency INTEGER NOT NULL,
    total              INTEGER NOT NULL,
    what_is_it         TEXT NOT NULL,
    why_might_it_win   TEXT NOT NULL,
    best_proof_point   TEXT NOT NULL,
    biggest_doubt      TEXT NOT NULL,
    why_spending_time  TEXT NOT NULL,
    deal_id            BIGINT NOT NULL UNIQUE REFERENCES deals(id)
);

CREATE TABLE IF NOT EXISTS decisions (
    id                        BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    status                    VARCHAR(255) NOT NULL,
    rationale                 TEXT NOT NULL,
    what_would_change_my_mind TEXT NOT NULL,
    next_milestone_needed     TEXT NOT NULL,
    deal_id                   BIGINT NOT NULL UNIQUE REFERENCES deals(id)
);

CREATE TABLE IF NOT EXISTS deep_diligence (
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    business_model_score   INTEGER NOT NULL,
    business_model_note    TEXT NOT NULL,
    market_customer_score  INTEGER NOT NULL,
    market_customer_note   TEXT NOT NULL,
    traction_quality_score INTEGER NOT NULL,
    traction_quality_note  TEXT NOT NULL,
    competitive_edge_score INTEGER NOT NULL,
    competitive_edge_note  TEXT NOT NULL,
    risk_score             INTEGER NOT NULL,
    risk_note              TEXT NOT NULL,
    total                  INTEGER NOT NULL,
    deal_id                BIGINT NOT NULL UNIQUE REFERENCES deals(id)
);

CREATE TABLE IF NOT EXISTS reviews (
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    next_review_date DATE NOT NULL,
    review_note      TEXT NOT NULL,
    thesis_direction VARCHAR(255) NOT NULL,
    deal_id          BIGINT NOT NULL UNIQUE REFERENCES deals(id)
);
