-- Phase 2 intelligence layer: configurable interests, interaction signals, structured company
-- changes with deterministic significance, and grounded trend metrics.
--
-- Additive only. No existing table is dropped or rewritten, and every new column carries a default
-- so the migration is safe on a populated database.

-- ---------------------------------------------------------------------------------------------
-- Configurable personal relevance. A single row keeps the profile trivially readable and editable;
-- the CHECK constraint prevents a second profile appearing by accident.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS radar_interest_profile (
    id             INTEGER PRIMARY KEY,
    interests_json TEXT NOT NULL,
    updated_at     TIMESTAMP NOT NULL,
    CONSTRAINT radar_interest_profile_single_row CHECK (id = 1)
);

-- ---------------------------------------------------------------------------------------------
-- Interaction signals. Recorded now so future personalisation has real history to learn from;
-- nothing here drives an opaque model today.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS radar_interaction_signals (
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id  BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    signal_type VARCHAR(40) NOT NULL,
    created_at  TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_radar_signals_company ON radar_interaction_signals(company_id, created_at DESC);
CREATE INDEX IF NOT EXISTS idx_radar_signals_type ON radar_interaction_signals(signal_type, created_at DESC);

-- ---------------------------------------------------------------------------------------------
-- Structured company changes. Snapshots previously stored a flat list of strings, which could not
-- express how much a change mattered. Significance is assigned deterministically.
-- ---------------------------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS radar_company_changes (
    id             BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id     BIGINT NOT NULL REFERENCES radar_companies(id) ON DELETE CASCADE,
    snapshot_id    BIGINT REFERENCES radar_company_snapshots(id) ON DELETE SET NULL,
    change_type    VARCHAR(60) NOT NULL,
    significance   VARCHAR(20) NOT NULL,
    summary        VARCHAR(500) NOT NULL,
    previous_value VARCHAR(1000),
    current_value  VARCHAR(1000),
    why_it_matters VARCHAR(1000),
    detected_at    TIMESTAMP NOT NULL
);

CREATE INDEX IF NOT EXISTS idx_radar_changes_company ON radar_company_changes(company_id, detected_at DESC);
CREATE INDEX IF NOT EXISTS idx_radar_changes_significance ON radar_company_changes(significance, detected_at DESC);

-- ---------------------------------------------------------------------------------------------
-- Accelerator provenance. Hacker News launch posts carry a reliable "(YC S26)" marker, and the
-- company profile is expected to show accelerator and batch.
-- ---------------------------------------------------------------------------------------------
ALTER TABLE radar_companies ADD COLUMN IF NOT EXISTS accelerator VARCHAR(120) NOT NULL DEFAULT '';
ALTER TABLE radar_companies ADD COLUMN IF NOT EXISTS accelerator_batch VARCHAR(40) NOT NULL DEFAULT '';

CREATE INDEX IF NOT EXISTS idx_radar_companies_batch ON radar_companies(accelerator_batch);

-- ---------------------------------------------------------------------------------------------
-- Trend grounding. Velocity is stored as raw counts so the UI can state absolute movement when
-- there is not enough history to justify a percentage.
-- ---------------------------------------------------------------------------------------------
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS why_it_matters TEXT NOT NULL DEFAULT '';
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS confidence VARCHAR(20) NOT NULL DEFAULT 'LOW';
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS recent_discoveries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS prior_discoveries INTEGER NOT NULL DEFAULT 0;
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS velocity_direction VARCHAR(20) NOT NULL DEFAULT 'UNKNOWN';
ALTER TABLE radar_trends ADD COLUMN IF NOT EXISTS velocity_note VARCHAR(300) NOT NULL DEFAULT '';
